// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylsguooyrfhgvxnapmwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlsc2d1b295cmZoZ3Z4bmFwbXd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDI2ODUsImV4cCI6MjA3MDUxODY4NX0.2xH5Lydiv6mwUg9T0tD86WztnHRLiKmSz4-damLCLYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});